// web/src/components/ui/Button.vue
<template>
  <button
    ref="buttonRef"
    :type="type"
    :disabled="isDisabled"
    :class="classes"
  >
    <span
      v-if="loading"
      class="h-3.5 w-3.5 animate-spin rounded-full border-2 border-current border-r-transparent"
      aria-hidden="true"
    />
    <span><slot /></span>
  </button>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { cn } from '@/utils/cn'

const props = withDefaults(
  defineProps<{
    variant?: 'primary' | 'secondary' | 'ghost' | 'destructive'
    loading?: boolean
    disabled?: boolean
    type?: 'button' | 'submit' | 'reset'
  }>(),
  {
    variant: 'secondary',
    loading: false,
    disabled: false,
    type: 'button',
  },
)

const isDisabled = computed(() => props.disabled || props.loading)
const buttonRef = ref<HTMLButtonElement | null>(null)

const variantClasses: Record<NonNullable<typeof props.variant>, string> = {
  primary: 'border-primary-600 bg-primary-600 text-white hover:border-primary-700 hover:bg-primary-700',
  secondary: 'border-ui-border bg-ui-panel text-ui-fg',
  ghost: 'border-transparent bg-transparent text-ui-fg',
  destructive: 'border-error bg-error text-white hover:bg-error/90',
}

const classes = computed(() =>
  cn(
    'ui-control ui-focus-ring ui-pressable inline-flex items-center justify-center gap-2 font-medium',
    variantClasses[props.variant],
    isDisabled.value && 'ui-disabled',
    props.loading && 'ui-loading',
  ),
)

defineExpose({
  focus: () => {
    buttonRef.value?.focus()
  },
})
</script>

// apps/desktop-tauri/src/components/ui/button.tsx
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import * as React from "react";

import { cn } from "@/lib/cn";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-control text-body font-medium transition-colors disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-background",
  {
    variants: {
      variant: {
        default: "bg-accent text-background hover:bg-accent/90",
        secondary: "bg-muted text-foreground hover:bg-muted/80",
        ghost: "bg-transparent text-muted-foreground hover:bg-muted/60 hover:text-foreground",
        destructive: "bg-destructive text-white hover:bg-destructive/90",
        outline: "border border-border bg-transparent text-foreground hover:bg-muted/60"
      },
      size: {
        default: "h-10 px-4",
        sm: "h-8 px-3 text-small",
        lg: "h-11 px-6",
        icon: "h-10 w-10"
      }
    },
    defaultVariants: {
      variant: "default",
      size: "default"
    }
  }
);

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(({ className, variant, size, asChild, ...props }, ref) => {
  const Comp = asChild ? Slot : "button";
  return <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />;
});
Button.displayName = "Button";

export { Button, buttonVariants };
